### ISSUE TITLE
proposed section heading change

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-leaf-gas-exchange#6]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-leaf-gas-exchange
* Submitter: Kim
* Justification (why is this change necessary?): help guide users to the essential components

I suggest the following changes: Change "Getting started" heading in README to "Getting started: links to instructions and templates". It's a bit clunky, but I think this change could help users in the GitBook, as the links to templates are only there as inline text, there is no separate folder for them. 

I realize that there is an effort to keep a consistent format across the different formats, but @robcrystalornelas would you be OK with adding this clarification?

**Comment by wavingtowaves** [comment]
@regnans Great suggestion Kim. I see how it's clear when you're on GitHub that there are downloadable templates since you can see the whole folder structure, and 'templates' is one of those folders--it's a lot less clear on GitBook.

I'd say go ahead and add that to the getting started heading, and I'll make that suggestion to the other CF Partner teams.

**Comment by regnans** [comment]
Thanks for your feedback. Update made.
