### ISSUE TITLE
Addition of Missing Value Codes to comply with CSV Reporting Format

### ISSUE THREAD

**Issue by dylanporyan** [ess-dive-community/essdive-leaf-gas-exchange#7]
* Documentation reference (URL): N/A
* Submitter: Dylan O'Ryan
* Justification (why is this change necessary?): To comply with the CSV Structure Reporting format [missing value codes](https://github.com/ess-dive-community/essdive-csv-structure/blob/master/csv_detailed_guide.md#missing-value-codes)

**I suggest the following changes:** While looking through the reporting format instructions and documents, I was unable to locate guidance for missing value codes (e.g., N/A and -9999) for the files. If not included in the reporting format information, I suggest adding this information to ensure that datasets using this reporting format will comply with the CSV reporting format guidance.

**Comment by regnans** [comment]
Hi Dylan,
Thanks for raising this issue. In developing this reporting format we deliberately avoided overlapping with the domains other reporting formats in order to not create conflicts or require cascading updates if something in another format changes. So that is why we don't specifically include guidance for csv formatting, including missing values. Other examples include not prescribing formats for sample information and locations as they are also covered elsewhere. The various reporting formats are intended to be modular and used together, i.e. a single data package may contain various data types that use different formats as appropriate. However, I don't think this is clear enough in the documentation (it is mentioned in the supplement metadata guide, but not specifically referring to the csv format). Would adding text to the documentation describing this modular approach, and referring users to other appropriate reporting formats be a satisfactory solution to this issue? My first thought would be to add this information to the Instructions, as a separate section so it has a bold heading. 
Kim

**Comment by dylanporyan** [comment]
Great, thank you for the clarification. Yes, I believe that adding some text in the documentation describing this would be the best solution to this issue. I agree that adding this in the instructions would be the best place for it. Thanks!

**Comment by regnans** [comment]
@dylanporyan The Instructions have been updated. If they are not clear, please let me know. Thanks again for your suggestion. 

@robcrystalornelas could you review this addition? It is probably relevant for other reporting formats also.  Once you approve I will created a new version. Thanks! https://github.com/ess-dive-community/essdive-leaf-gas-exchange/blob/master/instructions.md#use-of-this-format-with-other-ess-dive-reporting-formats

**Comment by wavingtowaves** [comment]
Hi @regnans, thanks so much for making those updates to the instructions. I agree, other teams will likely find the language there useful in order to explain how the formats are modular.  I reviewed the addition, and added just one minor change which was to add another link out to the ESS-DIVE community GitHub page at the very start of the first paragraph. I'll close the comment here, and you can go ahead and make that new version 👍🏻
